trigger:
  - lithium

pool:
  vmImage: 'ubuntu-latest'

variables:
  PythonVersion: '3.8'
  DockerBuildVersion: '1.0.1'
  DockerVersion: '17.09.0-ce'

steps:
  - task: UsePythonVersion@0
    displayName: Install Python runtime
    name: pyTools
    inputs:
      versionSpec: $(PythonVersion)
      addToPath: true
      architecture: 'x64'

  - task: DockerInstaller@0
    displayName: Install and start Docker daemon
    inputs:
      dockerVersion: $(DockerVersion)

  - script: $(pyTools.pythonLocation)/bin/pip install https://github.com/BunsenLabs/dockerbuild/releases/download/$(DockerBuildVersion)/dockerbuild-$(DockerBuildVersion)-py3-none-any.whl
    displayName: Install dockerbuild wheel

  - script: $(pyTools.pythonLocation)/bin/dockerbuild build -s $(Build.SourcesDirectory) -a amd64 -o $(Build.ArtifactStagingDirectory) -t 7200
    displayName: Build .deb package

  - script: |
      package_version=`head -n1 debian/changelog | cut -d' ' -f2 | tr -d '()' | tr '-' '.'`
      echo "##vso[task.setvariable variable=PackageVersion]$package_version"
    displayName: Export package version from debian/changelog

  - task: UniversalPackages@0
    inputs:
      command: 'publish'
      publishDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUsePublish: 'internal'
      vstsFeedPublish: '94f9b627-2fde-44fa-a54d-7cf14d37c1a3/a8d74501-7285-427f-9673-508c6169b38b'
      vstsFeedPackagePublish: 'bunsen-keyring'
      versionOption: 'custom'
      versionPublish: $(PackageVersion)